"""initial Brewline schema

Revision ID: 7de56633b2fd
Revises: 
Create Date: 2026-10-07 11:34:25.066692
"""
from collections.abc import Sequence

revision: str = '7de56633b2fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
